---
- name: update web servers
  hosts: webservers
  remote_user: root

  tasks:
  - name: Update packages based on package.json to their latest version.
  community.general.npm:
    path: /app
    state: latest