version: '3.8'
services:
  app:
    build: 
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
    environment:
      DATABASE_URL: "mysql://root@localhost:3306/nws-inventaire" # DEV URL DB
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysqldb-data:/var/lib/mysql
    network_mode: service:app

volumes:
  mysqldb-data: