version: '3.8'
services:
  app:
    build: 
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "${DATABASE_URL_TEST}" # URL DB
      GMAIL_APP_PASSWORD: "${GMAIL_APP_PASSWORD}"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: materiels
      MYSQL_USER: mkqdgnsdglxxgc98ftdq
      MYSQL_PASSWORD: "${DB_PASSWORD_TEST}"
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - 3306:3306
    volumes:
      - mysqldb-data:/var/lib/mysql
  reverse-proxy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80

volumes:
  mysqldb-data:
  caddy-data: