version: '3.8'
services:
  app:
    build: 
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "${DATABASE_URL}" # URL DB
      GMAIL_APP_PASSWORD: "${GMAIL_APP_PASSWORD}"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: materiels
      MYSQL_USER: nws_app
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - mysqldb-data:/var/lib/mysql

volumes:
  mysqldb-data:
  caddy-data: