name: Runs All Unit tests
run-name: Build and Tests

on:
  push:
    branches: [ci-cd]

jobs:
<<<<<<< HEAD
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push TO Github Repository
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: nws-material:latest
          target: nws-material
  build:
    runs-on: ubuntu-latest
    needs: [build-docker]
=======
  build:
    runs-on: ubuntu-latest
>>>>>>> 4ae1d3218de63f488b0ba41f39f8a018499a5205

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
<<<<<<< HEAD
      - uses: actions/setup-node@v3
=======
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
>>>>>>> 4ae1d3218de63f488b0ba41f39f8a018499a5205
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      #- run: npm run build --if-present
<<<<<<< HEAD
      - run: |
          npm ci
          npm run test
=======
      - name: Execute Unit tests
      - run: |
          npm ci
          npm run test
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v2  
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push TO Github Repository
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: nws-material:latest
          target: nws-material
>>>>>>> 4ae1d3218de63f488b0ba41f39f8a018499a5205
