name: Runs All Unit tests
run-name: Build and Tests

on: [push]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - name: Cache .nuxt
        id: cache-nuxt
        uses: actions/cache@v3
        with:
          path: .nuxt
          key: ${{ runner.os }}-nuxt-${{ github.run_id }}
      - run: |
          npm ci
          npm run build
  build-docker:
    needs: [build]
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io # lien pour registry github
          username: ${{ github.actor }} # actor github
          password: ${{ secrets.GITHUB_TOKEN }} # Génère un token de Github

      - name: Build and push to Github Repository
        uses: docker/build-push-action@v3
        with:
          push: true # push image dans le Github Registry
          tags: ghcr.io/matthiasfaucon/nws-material:latest # mettre un tag à l'image dans le Github Registry
          target: nws-material # sélectionner le Dockerfile
  test:
    needs: [build-docker]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - name: Cache .nuxt
        id: cache-nuxt
        uses: actions/cache@v3
        with:
          path: .nuxt
          key: ${{ runner.os }}-nuxt-${{ github.run_id }}
      - run: |
          docker compose up --build -d
          npm run test